name: humanity
description: "Humanity Mobile App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  intl: ^0.19.0
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.8
  math_expressions: ^2.0.0

  flutter_localizations: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    # - assets/fonts/
